const { SlashCommandBuilder } = require("discord.js");

module.exports = [
  new SlashCommandBuilder().setName("ping").setDescription("เช็คบอทออนไลน์"),
  new SlashCommandBuilder().setName("hello").setDescription("ทักทายบอท"),
  new SlashCommandBuilder().setName("time").setDescription("ดูเวลาปัจจุบัน"),
  new SlashCommandBuilder().setName("date").setDescription("ดูวันที่วันนี้"),
  new SlashCommandBuilder().setName("server").setDescription("ข้อมูลเซิร์ฟเวอร์"),
  new SlashCommandBuilder().setName("user").setDescription("ข้อมูลผู้ใช้"),
  new SlashCommandBuilder().setName("avatar").setDescription("ดูรูปโปรไฟล์"),
  new SlashCommandBuilder().setName("coin").setDescription("สุ่มหัวหรือก้อย"),
  new SlashCommandBuilder().setName("dice").setDescription("ทอยลูกเต๋า"),
  new SlashCommandBuilder().setName("random").setDescription("สุ่มตัวเลข"),
  new SlashCommandBuilder().setName("joke").setDescription("สุ่มมุกตลก"),
  new SlashCommandBuilder().setName("quote").setDescription("สุ่มคำคม"),
  new SlashCommandBuilder().setName("math").setDescription("คำนวณเลขง่าย ๆ"),
  new SlashCommandBuilder().setName("weather").setDescription("ดูสภาพอากาศ"),
  new SlashCommandBuilder().setName("profile").setDescription("ดูโปรไฟล์คุณ"),
  new SlashCommandBuilder().setName("rank").setDescription("ดูอันดับ"),
  new SlashCommandBuilder().setName("xp").setDescription("ดูค่า XP"),
  new SlashCommandBuilder().setName("level").setDescription("ดูเลเวล"),
  new SlashCommandBuilder().setName("invite").setDescription("ลิงก์เชิญบอท"),
  new SlashCommandBuilder().setName("help").setDescription("ดูคำสั่งทั้งหมด"),
  new SlashCommandBuilder().setName("about").setDescription("เกี่ยวกับบอท"),
  new SlashCommandBuilder().setName("uptime").setDescription("เวลาที่บอททำงาน"),
  new SlashCommandBuilder().setName("say").setDescription("ให้บอทพูดแทน"),
  new SlashCommandBuilder().setName("poll").setDescription("สร้างโพล"),
  new SlashCommandBuilder().setName("clear").setDescription("ลบข้อความ"),
  new SlashCommandBuilder().setName("kick").setDescription("เตะสมาชิก"),
  new SlashCommandBuilder().setName("ban").setDescription("แบนสมาชิก"),
  new SlashCommandBuilder().setName("mute").setDescription("ปิดเสียง"),
  new SlashCommandBuilder().setName("unmute").setDescription("เปิดเสียง"),
  new SlashCommandBuilder().setName("warn").setDescription("เตือนสมาชิก"),
  new SlashCommandBuilder().setName("warnings").setDescription("ดูการเตือน"),
  new SlashCommandBuilder().setName("lock").setDescription("ล็อกห้อง"),
  new SlashCommandBuilder().setName("unlock").setDescription("ปลดล็อกห้อง"),
  new SlashCommandBuilder().setName("giveaway").setDescription("สุ่มแจกของ"),
  new SlashCommandBuilder().setName("shop").setDescription("ร้านค้า"),
  new SlashCommandBuilder().setName("buy").setDescription("ซื้อไอเท็ม"),
  new SlashCommandBuilder().setName("balance").setDescription("ดูเงิน"),
  new SlashCommandBuilder().setName("daily").setDescription("รับเงินรายวัน"),
  new SlashCommandBuilder().setName("work").setDescription("ทำงานหาเงิน"),
  new SlashCommandBuilder().setName("rob").setDescription("ปล้นคนอื่น"),
  new SlashCommandBuilder().setName("leaderboard").setDescription("ตารางอันดับ"),
  new SlashCommandBuilder().setName("music").setDescription("คำสั่งเพลง"),
  new SlashCommandBuilder().setName("play").setDescription("เล่นเพลง"),
  new SlashCommandBuilder().setName("pause").setDescription("หยุดเพลง"),
  new SlashCommandBuilder().setName("resume").setDescription("เล่นต่อ"),
  new SlashCommandBuilder().setName("skip").setDescription("ข้ามเพลง"),
  new SlashCommandBuilder().setName("stop").setDescription("หยุดเพลงทั้งหมด"),
];
